"""empty message

Revision ID: 2f9324399ddd
Revises: f19416b1bb81
Create Date: 2022-08-08 18:42:30.388719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f9324399ddd"
down_revision = "f19416b1bb81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("societe_to_solution")
    op.alter_column("solution", "id", new_column_name="old_id")
    op.alter_column("solution", "new_id", new_column_name="id", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "solution",
        sa.Column("new_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_solution_wikidata_id", "solution", ["wikidata_id"], unique=False
    )
    op.drop_column("solution", "old_id")
    op.create_table(
        "societe_to_solution",
        sa.Column("societe_siren", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("solution_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["societe_siren"],
            ["societe.siren"],
            name="societe_to_solution_societe_siren_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["solution_id"],
            ["solution.id"],
            name="societe_to_solution_solution_id_fkey",
            onupdate="CASCADE",
        ),
    )
    # ### end Alembic commands ###
