"""empty message

Revision ID: 4b6e170b33c6
Revises: 2f9324399ddd
Create Date: 2022-08-08 19:06:52.300926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b6e170b33c6"
down_revision = "2f9324399ddd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("solution_pkey", table_name="solution")
    op.create_primary_key("solution_pkey", "solution", ["id"])
    op.alter_column("solution", "old_id", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index("ix_solution_wikidata_id", table_name="solution")
    op.create_table(
        "societe_to_solution",
        sa.Column("societe_siren", sa.String(), nullable=False),
        sa.Column("solution_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["societe_siren"], ["societe.siren"]),
        sa.ForeignKeyConstraint(["solution_id"], ["solution.id"], onupdate="cascade"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_solution_wikidata_id", "solution", ["wikidata_id"], unique=False
    )
    op.alter_column("solution", "old_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_table("societe_to_solution")
    # ### end Alembic commands ###
