"""empty message

Revision ID: 5026b4edb4a3
Revises: c7a1dbdd261c
Create Date: 2022-08-03 11:40:49.371655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5026b4edb4a3"
down_revision = "c7a1dbdd261c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("societe", sa.Column("description_short", sa.String(), nullable=True))
    op.add_column("societe", sa.Column("description_long", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("societe", "description_long")
    op.drop_column("societe", "description_short")
    # ### end Alembic commands ###
