"""empty message

Revision ID: 5a7f46342d1f
Revises: e195da700210
Create Date: 2022-02-01 17:34:41.496884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5a7f46342d1f"
down_revision = "e195da700210"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "etablissement",
        sa.Column(
            "_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column("societe", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "societe",
        sa.Column(
            "_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.drop_column("societe", "airtable_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "societe",
        sa.Column(
            "airtable_id",
            sa.VARCHAR(),
            server_default=sa.text("'\"'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("societe", "_json")
    op.drop_column("societe", "description")
    op.drop_column("etablissement", "_json")
    # ### end Alembic commands ###
