"""empty message

Revision ID: 6fdd57594d44
Revises: 4b6e170b33c6
Create Date: 2022-08-08 20:36:26.644633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fdd57594d44"
down_revision = "4b6e170b33c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("solution", sa.Column("_props", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("solution", "_props")
    # ### end Alembic commands ###
