"""empty message

Revision ID: b71bd66deabe
Revises: 6fdd57594d44
Create Date: 2022-08-08 22:40:25.876116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b71bd66deabe"
down_revision = "6fdd57594d44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("solution", sa.Column("slug", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("solution", "slug")
    # ### end Alembic commands ###
