"""empty message

Revision ID: c7a1dbdd261c
Revises: f378fbcfa222
Create Date: 2022-08-03 11:03:18.696278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7a1dbdd261c"
down_revision = "f378fbcfa222"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "societe",
        sa.Column(
            "site_web_down", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("societe", "site_web_down")
    # ### end Alembic commands ###
