"""empty message

Revision ID: f18d56f524e7
Revises: 5a7f46342d1f
Create Date: 2022-02-01 18:38:39.171142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f18d56f524e7"
down_revision = "5a7f46342d1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("logo", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "logo")
    # ### end Alembic commands ###
