"""empty message

Revision ID: f19416b1bb81
Revises: caf3d80bac61
Create Date: 2022-08-08 17:29:50.849083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f19416b1bb81"
down_revision = "caf3d80bac61"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "societe",
        "_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.add_column("solution", sa.Column("sill_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("solution", "sill_id")
    op.alter_column(
        "societe",
        "_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    # ### end Alembic commands ###
