"""empty message

Revision ID: f378fbcfa222
Revises: f18d56f524e7
Create Date: 2022-02-01 18:49:19.249044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f378fbcfa222"
down_revision = "f18d56f524e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster", sa.Column("_json", sa.JSON(), server_default="{}", nullable=False)
    )
    op.drop_column("cluster", "_extra")
    op.add_column(
        "solution", sa.Column("_json", sa.JSON(), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("solution", "_json")
    op.add_column(
        "cluster",
        sa.Column(
            "_extra",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("cluster", "_json")
    # ### end Alembic commands ###
